// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7yyJLGcJNJt1hGAjVFjLwwIpUPNZKNg',
    appId: '1:136719517391:web:18a69a773568386a69d9ba',
    messagingSenderId: '136719517391',
    projectId: 'karakoram-bids-d4352',
    authDomain: 'karakoram-bids-d4352.firebaseapp.com',
    storageBucket: 'karakoram-bids-d4352.firebasestorage.app',
    measurementId: 'G-BP487M3QQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIP5RXjJ0sYxZDSGPN0pARzfZGbMTVg60',
    appId: '1:136719517391:android:8d7c1c2785eabfc769d9ba',
    messagingSenderId: '136719517391',
    projectId: 'karakoram-bids-d4352',
    storageBucket: 'karakoram-bids-d4352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRqOOK3mhiNukecdY4DX1nHcf2NJ9jOE',
    appId: '1:136719517391:ios:1817c52265ef2d1969d9ba',
    messagingSenderId: '136719517391',
    projectId: 'karakoram-bids-d4352',
    storageBucket: 'karakoram-bids-d4352.firebasestorage.app',
    iosBundleId: 'com.example.myKarakoramBids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRqOOK3mhiNukecdY4DX1nHcf2NJ9jOE',
    appId: '1:136719517391:ios:1817c52265ef2d1969d9ba',
    messagingSenderId: '136719517391',
    projectId: 'karakoram-bids-d4352',
    storageBucket: 'karakoram-bids-d4352.firebasestorage.app',
    iosBundleId: 'com.example.myKarakoramBids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7yyJLGcJNJt1hGAjVFjLwwIpUPNZKNg',
    appId: '1:136719517391:web:66433f8e50f9701269d9ba',
    messagingSenderId: '136719517391',
    projectId: 'karakoram-bids-d4352',
    authDomain: 'karakoram-bids-d4352.firebaseapp.com',
    storageBucket: 'karakoram-bids-d4352.firebasestorage.app',
    measurementId: 'G-L9138S97V9',
  );
}
